// Generated by scripts/generate-stack-icons.mjs from the SVGs in this folder. Do not edit.
import type { IconSvgElement } from "@hugeicons/react";

export const AstralIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M2.5 12C2.5 7.52 2.5 5.28 3.89 3.89 5.28 2.5 7.52 2.5 12 2.5 16.48 2.5 18.72 2.5 20.11 3.89 21.5 5.28 21.5 7.52 21.5 12 21.5 16.48 21.5 18.72 20.11 20.11 18.72 21.5 16.48 21.5 12 21.5 7.52 21.5 5.28 21.5 3.89 20.11 2.5 18.72 2.5 16.48 2.5 12Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M7 17V8C7 7.45 7.45 7 8 7H16C16.55 7 17 7.45 17 8V17H7Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M12 17V14.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M10.75 11H13.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const AstroIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M4.6 14.4C6.4 13.65 8 13.2 9.6 13.2L11.5 7.45C11.6 7.15 11.8 7 12 7 12.2 7 12.4 7.15 12.5 7.45L14.4 13.2C16 13.2 17.6 13.65 19.4 14.4L15.2 3.15C15 2.7 14.8 2.5 14.5 2.5H9.5C9.2 2.5 9 2.7 8.8 3.15Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M9 16.5C10 17 11 17.15 12 17.15 13 17.15 14 17 15 16.5 15 18.4 13.9 19.9 12 21.25 10.1 19.9 9 18.4 9 16.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const BaseUiIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M5 3.25C7.98 3.25 10.4 6.38 10.4 10.25V20.75C7.42 20.75 5 17.87 5 14Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M12.85 8.45C16.25 8.45 19 11.2 19 14.6 19 18 16.25 20.75 12.85 20.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const BetterAuthIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.75 5.25L6.75 5.25C7.03 5.25 7.25 5.47 7.25 5.75L7.25 9C7.25 9.28 7.47 9.5 7.75 9.5L12.25 9.5 12.25 5.75C12.25 5.47 12.47 5.25 12.75 5.25L20.25 5.25C20.8 5.25 21.25 5.7 21.25 6.25L21.25 17.75C21.25 18.3 20.8 18.75 20.25 18.75L12.75 18.75C12.47 18.75 12.25 18.53 12.25 18.25L12.25 14.5 7.75 14.5C7.47 14.5 7.25 14.72 7.25 15L7.25 18.25C7.25 18.53 7.03 18.75 6.75 18.75L3.75 18.75C3.2 18.75 2.75 18.3 2.75 17.75L2.75 6.25C2.75 5.7 3.2 5.25 3.75 5.25Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M12.25 9.5L16.25 9.5C16.53 9.5 16.75 9.72 16.75 10L16.75 14C16.75 14.28 16.53 14.5 16.25 14.5L12.25 14.5 12.25 9.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const CloudflarePagesIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M10.25 4.75H6.25C5.15 4.75 4.25 5.65 4.25 6.75V17.25C4.25 18.35 5.15 19.25 6.25 19.25H8.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M16 4.75H17.75C18.85 4.75 19.75 5.65 19.75 6.75V17.25C19.75 18.35 18.85 19.25 17.75 19.25H14",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M13.9 2.6L12.9 10.25H17.25L10.4 21.4 11.1 13.75H6.75L13.9 2.6Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const ConvexIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M20.91 13.57C20.65 14.02 19.99 15.49 19.36 16.25 18.73 17.01 17.94 17.66 17.14 18.13 16.34 18.6 15.44 18.89 14.58 19.09 13.72 19.29 12.85 19.39 12 19.35 11.15 19.31 10.24 19.2 9.5 18.86 8.76 18.52 8.02 17.94 7.53 17.32 7.04 16.7 6.78 15.86 6.54 15.15 6.3 14.44 6.17 13.39 6.09 13.04",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M6.18 18.93C5.92 18.48 4.98 17.17 4.64 16.25 4.3 15.33 4.13 14.32 4.12 13.39 4.11 12.46 4.31 11.54 4.56 10.69 4.81 9.84 5.17 9.03 5.63 8.32 6.09 7.61 6.64 6.88 7.31 6.41 7.97 5.94 8.84 5.59 9.62 5.47 10.4 5.35 11.26 5.55 12 5.7 12.74 5.85 13.71 6.25 14.05 6.36",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M8.9 3.5C9.42 3.5 11.03 3.34 12 3.5 12.97 3.66 13.93 4.03 14.74 4.48 15.55 4.93 16.25 5.58 16.85 6.22 17.46 6.86 17.98 7.57 18.37 8.32 18.76 9.07 19.11 9.92 19.19 10.73 19.27 11.54 19.13 12.47 18.84 13.21 18.55 13.95 17.96 14.59 17.46 15.15 16.96 15.71 16.13 16.36 15.86 16.6",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const DockerIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M5 13V10H8V7H11V4H14V13",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8 10H14M11 7H14M8 10V13M11 7V13",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M3.25 13H15.5C16.25 13 16.75 12.75 17 12.5 16.4 11.5 16.5 10.1 17.3 9.1 18.2 9.6 18.85 10.4 19 11.25 20 11.1 21 11.25 21.5 11.75 21.1 12.8 20 13.5 18.6 13.5 17.4 16.85 14.6 20 9.25 20 5.25 20 2.75 18.25 2.75 13.5 2.75 13.25 3 13 3.25 13Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const DrizzleIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.36 16.27L5.98 11.3",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8.97 12.7L11.78 7.73",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M12.22 16.27L14.88 11.3",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M17.97 12.7L20.65 7.73",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const EslintIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.33 8.88C2.44 10.4 2 11.16 2 12 2 12.84 2.44 13.6 3.33 15.12L4.94 17.88C5.83 19.4 6.27 20.16 7 20.58 7.73 21 8.62 21 10.39 21H13.61C15.38 21 16.27 21 17 20.58 17.73 20.16 18.17 19.4 19.06 17.88L20.67 15.12C21.56 13.6 22 12.84 22 12 22 11.16 21.56 10.4 20.67 8.88L19.06 6.12C18.17 4.6 17.73 3.84 17 3.42 16.27 3 15.38 3 13.61 3H10.39C8.62 3 7.73 3 7 3.42 6.27 3.84 5.83 4.6 4.94 6.12L3.33 8.88Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M12.65 7.38L15.68 9.12C16.04 9.33 16.33 9.84 16.33 10.25L16.33 13.75C16.33 14.16 16.04 14.67 15.68 14.88L12.65 16.62C12.29 16.83 11.71 16.83 11.35 16.62L8.32 14.88C7.96 14.67 7.67 14.16 7.67 13.75L7.67 10.25C7.67 9.84 7.96 9.33 8.32 9.12L11.35 7.38C11.71 7.17 12.29 7.17 12.65 7.38Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const FastapiIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "9.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M11.38 7H17.23L11.36 11.12H15.37L6.82 17.13 11.38 7Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const FlaskIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3 7.75L10.75 4.5C11 6.5 11.4 9.3 12 11.7 13.2 15.5 15.8 17.6 20.5 17 20.95 16.95 21.15 17.4 20.8 17.7 17 20.1 11.5 20.2 8 16.6 5.6 14.2 4 11.1 3 7.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M4.7 12.3L11.35 9.35",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M6.85 15.45L12.6 12.9",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const FlutterIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M13.76 2.88L4.63 12 7.44 14.81 19.36 2.88Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M13.77 11.3L8.85 16.2 13.77 21.12H19.37L14.46 16.2 19.37 11.3Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const GinIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M5 6.25H19L17.6 19.6C17.5 20.65 16.6 21.5 15.5 21.5H8.5C7.4 21.5 6.5 20.65 6.4 19.6L5 6.25Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M14.25 6.25C14.25 4.6 15.6 3.25 17.25 3.25 18.9 3.25 20.25 4.6 20.25 6.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "circle",
    {
      cx: "9.75",
      cy: "13.5",
      r: "1.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "circle",
    {
      cx: "14.25",
      cy: "13.5",
      r: "1.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const GitIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M10.6 2.9L2.9 10.6C2.13 11.37 2.13 12.63 2.9 13.4L10.6 21.1C11.37 21.87 12.63 21.87 13.4 21.1L21.1 13.4C21.87 12.63 21.87 11.37 21.1 10.6L13.4 2.9C12.63 2.13 11.37 2.13 10.6 2.9Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "circle",
    {
      cx: "12",
      cy: "8",
      r: "1.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "circle",
    {
      cx: "12",
      cy: "16",
      r: "1.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "circle",
    {
      cx: "16",
      cy: "12",
      r: "1.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M8.75 4.75L10.94 6.94M12 9.5V14.5M13.06 9.06L14.94 10.94",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
];

export const GithubActionsIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "6.5",
      cy: "6.5",
      r: "3.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M5.5 5.25L8 6.5 5.5 7.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M6.5 10V16C6.5 17.52 7.73 18.75 9.25 18.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M6.5 10C6.5 11.24 7.51 12.25 8.75 12.25H9.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "circle",
    {
      cx: "11.75",
      cy: "12.25",
      r: "2.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M10.6 12.3L11.35 13.05 12.9 11.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "5",
    },
  ],
  [
    "path",
    {
      d: "M14.25 12.25H16.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "6",
    },
  ],
  [
    "circle",
    {
      cx: "18.75",
      cy: "12.25",
      r: "2.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "7",
    },
  ],
  [
    "path",
    {
      d: "M17.6 12.3L18.35 13.05 19.9 11.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "8",
    },
  ],
  [
    "circle",
    {
      cx: "11.75",
      cy: "18.75",
      r: "2.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "9",
    },
  ],
];

export const GoIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M14.36 9.91C13.56 8.7 11.88 8.4 10.37 9.18 8.87 9.97 7.97 11.63 8.25 13.11 8.53 14.59 9.9 15.47 11.5 15.2 13.1 14.93 14.47 13.58 14.75 12H11.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M21.5 12C21.18 13.79 19.47 15.25 17.68 15.25 15.88 15.25 14.68 13.79 15 12 15.32 10.21 17.03 8.75 18.82 8.75 20.62 8.75 21.82 10.21 21.5 12Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M4.81 10.25H6.56",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M2.62 12.75H5.62",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const GsapIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M6.73 9.75C7.02 8.4 6.41 7.5 5.46 7.5 4.31 7.5 3.21 8.66 2.84 10.39L2.16 13.61C1.79 15.34 2.39 16.5 3.54 16.5 4.59 16.5 5.51 15.47 5.84 13.93L6.18 12.32H4.58",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M11.52 9.56C11.77 8.4 11.21 7.5 10.21 7.5 9.21 7.5 8.27 8.4 8.02 9.56 7.77 10.71 8.29 11.36 9.28 11.87 10.27 12.39 10.75 13.16 10.48 14.44 10.23 15.6 9.29 16.5 8.29 16.5 7.29 16.5 6.73 15.6 6.98 14.44",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M11.29 16.5L15.21 7.5 15.29 16.5M12.56 13.61H15.26",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M16.54 16.5L18.46 7.5H20.21C21.18 7.5 21.74 8.5 21.48 9.75L21.41 10.07C21.14 11.32 20.15 12.32 19.18 12.32H17.43",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const HetznerIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M2.5 12C2.5 7.52 2.5 5.28 3.89 3.89 5.28 2.5 7.52 2.5 12 2.5 16.48 2.5 18.72 2.5 20.11 3.89 21.5 5.28 21.5 7.52 21.5 12 21.5 16.48 21.5 18.72 20.11 20.11 18.72 21.5 16.48 21.5 12 21.5 7.52 21.5 5.28 21.5 3.89 20.11 2.5 18.72 2.5 16.48 2.5 12Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M7.5 6.75V17.25M16.5 6.75V17.25M7.5 12H16.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const JinjaIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M2.5 3.25C5.5 4.75 8.75 5.25 12 5.25 15.25 5.25 18.5 4.75 21.5 3.25L20.5 7.25H3.5L2.5 3.25Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M4 11.5H20",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M7.25 7.25V21M16.75 7.25V21M12 7.25V11.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const NextjsIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "9.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8.85 15.25V8.75L17.6 19.4",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M15.25 8.75V13.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const OxcIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M9.75 2.85H14.25C14.5 2.85 14.75 3.1 14.75 3.35V5.6C14.75 6.1 15.15 6.5 15.65 6.5H18.9C19.4 6.5 19.65 7.1 19.3 7.45L15 11.75C14.85 11.9 14.75 12.15 14.75 12.4V13.9C14.75 14.5 15.35 14.95 15.9 14.65 16.45 14.35 17 14 17.5 13.55 17.7 13.4 18 13.4 18.15 13.55L21.35 16.8C21.55 17 21.55 17.25 21.35 17.45 18.9 19.75 15.6 21.15 12 21.15 8.4 21.15 5.1 19.75 2.65 17.45 2.45 17.25 2.45 17 2.65 16.8L5.85 13.55C6 13.4 6.3 13.4 6.5 13.55 7 14 7.55 14.35 8.1 14.65 8.65 14.95 9.25 14.5 9.25 13.9V12.4C9.25 12.15 9.15 11.9 9 11.75L4.7 7.45C4.35 7.1 4.6 6.5 5.1 6.5H8.35C8.85 6.5 9.25 6.1 9.25 5.6V3.35C9.25 3.1 9.5 2.85 9.75 2.85Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
];

export const PnpmIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.5 2.5L6.25 2.5C6.8 2.5 7.25 2.95 7.25 3.5L7.25 6.25C7.25 6.8 6.8 7.25 6.25 7.25L3.5 7.25C2.95 7.25 2.5 6.8 2.5 6.25L2.5 3.5C2.5 2.95 2.95 2.5 3.5 2.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M10.63 2.5L13.38 2.5C13.93 2.5 14.38 2.95 14.38 3.5L14.38 6.25C14.38 6.8 13.93 7.25 13.38 7.25L10.63 7.25C10.07 7.25 9.63 6.8 9.63 6.25L9.63 3.5C9.63 2.95 10.07 2.5 10.63 2.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M17.75 2.5L20.5 2.5C21.05 2.5 21.5 2.95 21.5 3.5L21.5 6.25C21.5 6.8 21.05 7.25 20.5 7.25L17.75 7.25C17.2 7.25 16.75 6.8 16.75 6.25L16.75 3.5C16.75 2.95 17.2 2.5 17.75 2.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M10.63 9.63L13.38 9.63C13.93 9.63 14.38 10.07 14.38 10.63L14.38 13.38C14.38 13.93 13.93 14.38 13.38 14.38L10.63 14.38C10.07 14.38 9.63 13.93 9.63 13.38L9.63 10.63C9.63 10.07 10.07 9.63 10.63 9.63Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M17.75 9.63L20.5 9.63C21.05 9.63 21.5 10.07 21.5 10.63L21.5 13.38C21.5 13.93 21.05 14.38 20.5 14.38L17.75 14.38C17.2 14.38 16.75 13.93 16.75 13.38L16.75 10.63C16.75 10.07 17.2 9.63 17.75 9.63Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M3.5 16.75L6.25 16.75C6.8 16.75 7.25 17.2 7.25 17.75L7.25 20.5C7.25 21.05 6.8 21.5 6.25 21.5L3.5 21.5C2.95 21.5 2.5 21.05 2.5 20.5L2.5 17.75C2.5 17.2 2.95 16.75 3.5 16.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "5",
    },
  ],
  [
    "path",
    {
      d: "M10.63 16.75L13.38 16.75C13.93 16.75 14.38 17.2 14.38 17.75L14.38 20.5C14.38 21.05 13.93 21.5 13.38 21.5L10.63 21.5C10.07 21.5 9.63 21.05 9.63 20.5L9.63 17.75C9.63 17.2 10.07 16.75 10.63 16.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "6",
    },
  ],
  [
    "path",
    {
      d: "M17.75 16.75L20.5 16.75C21.05 16.75 21.5 17.2 21.5 17.75L21.5 20.5C21.5 21.05 21.05 21.5 20.5 21.5L17.75 21.5C17.2 21.5 16.75 21.05 16.75 20.5L16.75 17.75C16.75 17.2 17.2 16.75 17.75 16.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "7",
    },
  ],
];

export const PostgresqlIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M10 3.75C8.5 3.1 6 2.75 4.5 3.9 3.3 4.8 2.9 6.3 3.1 8 3.4 10.6 4.4 14.1 5.6 15.7 6.4 16.8 7.4 16.4 8.2 15.4L9.5 14C10.6 14.6 11.5 15.2 11.6 16.5V19C11.6 20.5 12.6 21.5 14 21.5 15.6 21.5 16.6 20.5 16.75 19L17 16C18.5 16 20.3 15.5 20.75 14.5 20.9 14.1 20.6 13.9 20 14 19.2 14.15 18.6 14.2 18.2 14 19.8 11.5 20.8 9.5 21 7.2 21.2 5 19.5 3 16.5 2.9 15.5 2.9 14.5 3.1 13.75 3.35 12.5 3 11 3.1 10 3.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M10 3.75C8.4 5.4 8 7.6 8.05 9.5 8.1 11 8.4 12.8 9.5 14",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M13.75 3.35C16 4.4 17.5 6 17.6 8.5 17.7 10.6 17.6 12.4 18.2 14",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M10.75 9H10.76M15.25 9H15.26",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const PrettierIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M4.25 3.5H15",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M4.25 7H7M10 7H18",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M4.25 10.5H9M16 10.5H19.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M4.25 14H6M9 14H16",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M4.25 17.5H8.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M4.25 21H6.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "5",
    },
  ],
];

export const PydanticIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M12.44 4.36L20.56 15.64C20.8 15.98 20.69 16.39 20.31 16.55L12.69 19.95C12.31 20.11 11.69 20.11 11.31 19.95L3.69 16.55C3.31 16.39 3.2 15.98 3.44 15.64L11.56 4.36C11.8 4.02 12.2 4.02 12.44 4.36Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M6.15 11.85L12 9.6 17.85 11.85",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M12 9.6V20.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const PytestIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.5 3.75H20.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M5.7 7V20.75M9.9 7V17.5M14.05 7V14.25M18.2 7V11",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const RadixUiIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M6.5 2.75L9.75 2.75C10.3 2.75 10.75 3.2 10.75 3.75L10.75 7C10.75 7.55 10.3 8 9.75 8L6.5 8C5.95 8 5.5 7.55 5.5 7L5.5 3.75C5.5 3.2 5.95 2.75 6.5 2.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "circle",
    {
      cx: "15.88",
      cy: "5.38",
      r: "2.63",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M10.75 10.75V21.25C7.85 21.25 5.5 18.9 5.5 16 5.5 13.1 7.85 10.75 10.75 10.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const RailwayIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "9.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M3.58 7.6H11C13.3 7.6 15.2 8.4 16.6 10.1 17.6 11.3 18 12.5 17.5 13.5 17.2 14.1 16.6 14.5 15.8 14.5H2.83",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M2.53 11.25H14.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const ReactHookFormIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M6.25 4L17.75 4C18.99 4 20 5.01 20 6.25L20 19.25C20 20.49 18.99 21.5 17.75 21.5L6.25 21.5C5.01 21.5 4 20.49 4 19.25L4 6.25C4 5.01 5.01 4 6.25 4Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8.75 4V5C8.75 6.1 9.65 7 10.75 7H13.25C14.35 7 15.25 6.1 15.25 5V4",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M10.5 4C10.5 3.17 11.17 2.5 12 2.5 12.83 2.5 13.5 3.17 13.5 4",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M7.25 11.5H10.75M13.25 11.5H16.75M7.25 16.5H10.75M13.25 16.5H16.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const RuffIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M2.5 12C2.5 7.52 2.5 5.28 3.89 3.89 5.28 2.5 7.52 2.5 12 2.5 16.48 2.5 18.72 2.5 20.11 3.89 21.5 5.28 21.5 7.52 21.5 12 21.5 16.48 21.5 18.72 20.11 20.11 18.72 21.5 16.48 21.5 12 21.5 7.52 21.5 5.28 21.5 3.89 20.11 2.5 18.72 2.5 16.48 2.5 12Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8.25 15.75V8.25H14.75C15.3 8.25 15.75 8.7 15.75 9.25V11.25C15.75 11.8 15.3 12.25 14.75 12.25H8.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M12.75 12.25H14.75C15.3 12.25 15.75 12.7 15.75 13.25V15.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const SpringBootIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.33 8.88C2.44 10.4 2 11.16 2 12 2 12.84 2.44 13.6 3.33 15.12L4.94 17.88C5.83 19.4 6.27 20.16 7 20.58 7.73 21 8.62 21 10.39 21H13.61C15.38 21 16.27 21 17 20.58 17.73 20.16 18.17 19.4 19.06 17.88L20.67 15.12C21.56 13.6 22 12.84 22 12 22 11.16 21.56 10.4 20.67 8.88L19.06 6.12C18.17 4.6 17.73 3.84 17 3.42 16.27 3 15.38 3 13.61 3H10.39C8.62 3 7.73 3 7 3.42 6.27 3.84 5.83 4.6 4.94 6.12L3.33 8.88Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M14.89 8.55C16.34 9.77 16.88 11.76 16.23 13.54 15.58 15.32 13.89 16.5 12 16.5 10.11 16.5 8.42 15.32 7.77 13.54 7.12 11.76 7.66 9.77 9.11 8.55",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M12 6.5V11.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const TanstackQueryIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M12 8C17.52 8 22 9.79 22 12 22 14.21 17.52 16 12 16 6.48 16 2 14.21 2 12 2 9.79 6.48 8 12 8Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M15.56 9.98C18.4 14.82 19.1 19.65 17.14 20.77 15.17 21.89 11.28 18.87 8.44 14.02 5.6 9.18 4.9 4.35 6.86 3.23 8.83 2.11 12.72 5.13 15.56 9.98Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M15.56 14.02C12.72 18.87 8.83 21.89 6.86 20.77 4.9 19.65 5.6 14.82 8.44 9.98 11.28 5.13 15.17 2.11 17.14 3.23 19.1 4.35 18.4 9.18 15.56 14.02Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M14 12.43L13.38 13.52C13.24 13.76 12.91 13.95 12.63 13.95L11.38 13.95C11.1 13.95 10.77 13.76 10.63 13.52L10 12.43C9.86 12.19 9.86 11.81 10 11.57L10.63 10.48C10.77 10.24 11.1 10.05 11.38 10.05L12.63 10.05C12.91 10.05 13.24 10.24 13.38 10.48L14 11.57C14.14 11.81 14.14 12.19 14 12.43Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const TanstackIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M12 2.75C16.9 2.75 19 5.9 19 12 19 18.1 16.9 21.25 12 21.25 7.1 21.25 5 18.1 5 12 5 5.9 7.1 2.75 12 2.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M12 7.75C10.6 5.9 8.2 5.6 6.75 7.25M12 7.75C13.4 5.9 15.8 5.6 17.25 7.25M12 7.75C10.4 8 9 9.1 8.5 10.75M12 7.75C13.6 8 15 9.1 15.5 10.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M12 7.75V15.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M7.75 16.25C9.25 16.25 9.25 15.5 10.6 15.5 11.6 15.5 11.75 16.25 12 16.25 12.25 16.25 12.4 15.5 13.4 15.5 14.75 15.5 14.75 16.25 16.25 16.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const TurborepoIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "5.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M12.65 2.77C17.38 3.1 21.1 6.94 21.26 11.68 21.42 16.41 17.98 20.51 13.29 21.16",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M10.71 21.16C9.16 20.94 7.68 20.33 6.43 19.39",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M4.61 17.57C3.53 16.14 2.9 14.43 2.77 12.65",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const UvIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M12 2.75H2.75V19.25C2.75 20.35 3.65 21.25 4.75 21.25H17C18.1 21.25 19 20.35 19 19.5H21.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M21.25 21.25V2.75H12V14.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const VaadinIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.4 3.85V5C3.4 6.1 4.1 6.8 5.4 6.8H9.7C11.3 6.8 12 7.6 12 9.2 12 7.6 12.7 6.8 14.3 6.8H18.6C19.9 6.8 20.6 6.1 20.6 5V3.85",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8 12.6L12 19.95 16 12.6",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const VercelIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M12.63 4.83L20.61 18.67C20.96 19.27 20.68 19.75 19.99 19.75L4.01 19.75C3.32 19.75 3.04 19.27 3.39 18.67L11.37 4.83C11.72 4.23 12.28 4.23 12.63 4.83Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
];

export const ViteIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M7.73 3.57L17.96 3.57C18.37 3.57 18.51 3.84 18.27 4.18L14.96 8.77C14.72 9.11 14.86 9.38 15.27 9.38L20.48 9.38C20.89 9.38 21.02 9.65 20.77 9.97L12.46 20.66C12.21 20.98 12 20.91 12 20.5L12 15.68C12 15.27 11.66 14.93 11.25 14.93L6.88 14.93C6.47 14.93 6.33 14.66 6.58 14.33L9.88 9.98C10.13 9.65 9.99 9.38 9.58 9.38L3.52 9.38C3.11 9.38 2.97 9.11 3.21 8.77L6.54 4.18C6.78 3.84 7.32 3.57 7.73 3.57Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
];

export const VitestIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.87 7.68L7.97 10.54C8.54 10.93 9.29 10.77 9.64 10.18L13.37 3.89C13.58 3.54 14.09 3.25 14.5 3.25L19.75 3.25C20.16 3.25 20.34 3.55 20.15 3.91L11.72 19.62C11.46 20.11 10.89 20.24 10.44 19.92L3.86 15.19C3.52 14.95 3.25 14.41 3.25 14L3.25 8C3.25 7.59 3.53 7.44 3.87 7.68Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
];

export const ZedIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.25 17.25V4.25C3.25 3.7 3.7 3.25 4.25 3.25H20.75L3.25 20.75H19.75C20.3 20.75 20.75 20.3 20.75 19.75V6.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M6.75 14V7.75C6.75 7.2 7.2 6.75 7.75 6.75H17.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M17.25 10V16.25C17.25 16.8 16.8 17.25 16.25 17.25H6.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const ZodIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M6.8 4.5L17.2 4.5C18.03 4.5 18.93 5.13 19.21 5.91L20.74 10.19C21.02 10.97 20.75 12.04 20.12 12.59L13.31 18.59C12.59 19.23 11.41 19.23 10.69 18.59L3.88 12.59C3.25 12.04 2.98 10.97 3.26 10.19L4.79 5.91C5.07 5.13 5.97 4.5 6.8 4.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M5.75 9.25H14.25L7.5 13.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M14 13.5H17.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const ZustandIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "13.25",
      r: "7.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M6.01 8.74C4.7 8.86 3.47 8.11 2.97 6.9 2.47 5.69 2.82 4.29 3.82 3.45 4.83 2.61 6.26 2.52 7.36 3.23 8.47 3.93 8.98 5.28 8.64 6.54",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M15.36 6.54C15.02 5.28 15.53 3.93 16.64 3.23 17.74 2.52 19.17 2.61 20.18 3.45 21.18 4.29 21.53 5.69 21.03 6.9 20.53 8.11 19.3 8.86 17.99 8.74",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M9.25 11.75H9.26M14.75 11.75H14.76",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M12 14.25C13.66 14.25 15 15.37 15 16.75 15 18.13 13.66 19.25 12 19.25 10.34 19.25 9 18.13 9 16.75 9 15.37 10.34 14.25 12 14.25Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M11.25 16.25H12.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "5",
    },
  ],
];
