// Generated by scripts/generate-stack-icons.mjs from the SVGs in this folder. Do not edit.
import type { IconSvgElement } from "@hugeicons/react";

export const AstralIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M2.5 12C2.5 7.52166 2.5 5.28249 3.89124 3.89124C5.28249 2.5 7.52166 2.5 12 2.5C16.4783 2.5 18.7175 2.5 20.1088 3.89124C21.5 5.28249 21.5 7.52166 21.5 12C21.5 16.4783 21.5 18.7175 20.1088 20.1088C18.7175 21.5 16.4783 21.5 12 21.5C7.52166 21.5 5.28249 21.5 3.89124 20.1088C2.5 18.7175 2.5 16.4783 2.5 12Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8 17V10C8 8.34315 9.34315 7 11 7H13C14.6569 7 16 8.34315 16 10V17",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M11 11H13",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const AstroIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M5.5 18L9.80385 4.62337C10.1103 3.65045 10.9993 3 12 3C13.0007 3 13.8897 3.65045 14.1962 4.62337L18.5 18C16.5 16.8 14.4 16.2 12 16.2C9.6 16.2 7.5 16.8 5.5 18Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M10 19C10 20.3 10.9 21.3 12 22C13.1 21.3 14 20.3 14 19",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const BaseUiIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M5.5 3.5C8.26142 3.5 10.5 5.73858 10.5 8.5V20.5C7.73858 20.5 5.5 18.2614 5.5 15.5V3.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M13 9.5C16.0376 9.5 18.5 11.9624 18.5 15C18.5 18.0376 16.0376 20.5 13 20.5V9.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const BetterAuthIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.5 5.5C3.5 4.94772 3.94772 4.5 4.5 4.5H8.5V19.5H4.5C3.94772 19.5 3.5 19.05 3.5 18.5V5.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8.5 9.5H15.5V14.5H8.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M12.5 4.5H19.5C20.0523 4.5 20.5 4.94772 20.5 5.5V18.5C20.5 19.0523 20.0523 19.5 19.5 19.5H12.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const CloudflarePagesIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M9.5 3.5H6C4.89543 3.5 4 4.39543 4 5.5V18.5C4 19.6046 4.89543 20.5 6 20.5H8",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M14.5 20.5H18C19.1046 20.5 20 19.6046 20 18.5V5.5C20 4.39543 19.1046 3.5 18 3.5H16",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M14 2L8.5 12.5H13L10 22L16 10.5H11.5L14 2Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const ConvexIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "10",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M12 2C9 5 8.8 9.8 12 12",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M20.6603 17C19.5622 12.9019 15.5053 10.3287 12 12",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M3.3397 17C7.4378 18.0981 11.6947 15.8713 12 12",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const DockerIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M2.5 12.5H19.5C19.8 11 20.8 10 22 10C21.9 11.3 21.3 12.3 20.4 12.8C19.6 17.6 15.6 20.5 10.5 20.5C6 20.5 3 17.5 2.5 12.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M5 12.5V9H16.5V12.5M8.8 9V12.5M12.7 9V12.5M8.8 9V5.5H12.7V9",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const DrizzleIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.5 16L6 11.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8.5 12.5L11 8",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M13 16L15.5 11.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M18 12.5L20.5 8",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const EslintIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.32966 8.88231C2.44322 10.4038 2 11.1646 2 12C2 12.8354 2.44322 13.5962 3.32966 15.1177L4.94031 17.8823C5.82675 19.4038 6.26997 20.1646 7 20.5823C7.73003 21 8.61647 21 10.3894 21H13.6106C15.3835 21 16.27 21 17 20.5823C17.73 20.1646 18.1733 19.4038 19.0597 17.8823L20.6703 15.1177C21.5568 13.5962 22 12.8354 22 12C22 11.1646 21.5568 10.4038 20.6703 8.88231L19.0597 6.11769C18.1733 4.59615 17.73 3.83538 17 3.41769C16.27 3 15.3835 3 13.6106 3H10.3894C8.61647 3 7.73003 3 7 3.41769C6.26997 3.83538 5.82675 4.59615 4.94031 6.11769L3.32966 8.88231Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M12 7.25L16.1136 9.625L16.1136 14.375L12 16.75L7.8864 14.375L7.8864 9.625Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const FastapiIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "10",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M13.5 5.5L8 13H12L10.5 18.5L16 11H12L13.5 5.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const FlaskIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.5 5L9.5 3C9.5 9.5 13.5 16.5 20.5 18.5C17.5 21.5 9.5 20 6 12.5C4.8 10 4 7.5 3.5 5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M4.6 9L10 7.2",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M6.5 13.5L12 10.7",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const FlutterIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M14 2.5L4.5 12L7.5 15L20 2.5H14Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M14 11.5L8.5 17L14 22.5H20L14.5 17L20 11.5H14Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const GinIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M5 6H19L17.6 19.4C17.5 20.6 16.5 21.5 15.3 21.5H8.7C7.5 21.5 6.5 20.6 6.4 19.4L5 6Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M5.6 10.5H18.4",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M15.5 6C15.5 3.8 17 2.5 19.5 2.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "circle",
    {
      cx: "10",
      cy: "14.5",
      r: "1.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "circle",
    {
      cx: "14",
      cy: "14.5",
      r: "1.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
];

export const GitIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M10.6 2.9L2.9 10.6C2.1268 11.3732 2.1268 12.6268 2.9 13.4L10.6 21.1C11.3732 21.8732 12.6268 21.8732 13.4 21.1L21.1 13.4C21.8732 12.6268 21.8732 11.3732 21.1 10.6L13.4 2.9C12.6268 2.1268 11.3732 2.1268 10.6 2.9Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M7.5 6.5L10 9M11 11V14.5M12.3 10.8L14.2 12.4",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "circle",
    {
      cx: "11",
      cy: "10",
      r: "1.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "circle",
    {
      cx: "11",
      cy: "16",
      r: "1.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "circle",
    {
      cx: "15.5",
      cy: "13.5",
      r: "1.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
];

export const GithubActionsIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "6",
      cy: "6",
      r: "3.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M5 4.5L7.5 6L5 7.5V4.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M9.5 6H14.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "circle",
    {
      cx: "18",
      cy: "6",
      r: "3.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M16.5 6.1L17.5 7.1L19.5 5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M6 9.5V14C6 16.2091 7.79086 18 10 18H14.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "5",
    },
  ],
  [
    "circle",
    {
      cx: "18",
      cy: "18",
      r: "3.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "6",
    },
  ],
  [
    "path",
    {
      d: "M16.5 18.1L17.5 19.1L19.5 17",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "7",
    },
  ],
];

export const GoIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M12.4017 9.3483A3.75 3.75 0 1 0 13.5 12.75H10.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "circle",
    {
      cx: "18",
      cy: "12",
      r: "3.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M2 10.5H3.5M1.5 13.5H3",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const GsapIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M9 3H14C14.5523 3 15 3.44772 15 4V12L18.9 15.9C20.3 17.3 20.3 19.6 18.9 21C17.5 22.4 15.2 22.4 13.8 21L9.17 16.37C8.42 15.62 8 14.6 8 13.54V4C8 3.44772 8.44772 3 9 3Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8 6.5H15",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M15.5 19.5L17.5 17.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const HetznerIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M2.5 12C2.5 7.52166 2.5 5.28249 3.89124 3.89124C5.28249 2.5 7.52166 2.5 12 2.5C16.4783 2.5 18.7175 2.5 20.1088 3.89124C21.5 5.28249 21.5 7.52166 21.5 12C21.5 16.4783 21.5 18.7175 20.1088 20.1088C18.7175 21.5 16.4783 21.5 12 21.5C7.52166 21.5 5.28249 21.5 3.89124 20.1088C2.5 18.7175 2.5 16.4783 2.5 12Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8.5 7V17M15.5 7V17M8.5 12H15.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const JinjaIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M2.5 3.5C5.5 4.8 18.5 4.8 21.5 3.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M4.5 8H19.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M7 5V21",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M17 5V21",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M12 5.5V8",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
];

export const NextjsIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "10",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8.5 16V8L17.5 19.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M15.5 8V13",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const OxcIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M9 3H15V8H18.5L12 14L5.5 8H9V3Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M3 15.5L7.5 14C8.5 15.8 10.1 17 12 17C13.9 17 15.5 15.8 16.5 14L21 15.5C19.7 19 16.2 21.5 12 21.5C7.8 21.5 4.3 19 3 15.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const PnpmIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M4 3H7C7.5523 3 8 3.4477 8 4V7C8 7.5523 7.5523 8 7 8H4C3.4477 8 3 7.5523 3 7V4C3 3.4477 3.4477 3 4 3Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M10.5 3H13.5C14.0523 3 14.5 3.4477 14.5 4V7C14.5 7.5523 14.0523 8 13.5 8H10.5C9.9477 8 9.5 7.5523 9.5 7V4C9.5 3.4477 9.9477 3 10.5 3Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M17 3H20C20.5523 3 21 3.4477 21 4V7C21 7.5523 20.5523 8 20 8H17C16.4477 8 16 7.5523 16 7V4C16 3.4477 16.4477 3 17 3Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M10.5 9.5H13.5C14.0523 9.5 14.5 9.9477 14.5 10.5V13.5C14.5 14.0523 14.0523 14.5 13.5 14.5H10.5C9.9477 14.5 9.5 14.0523 9.5 13.5V10.5C9.5 9.9477 9.9477 9.5 10.5 9.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M17 9.5H20C20.5523 9.5 21 9.9477 21 10.5V13.5C21 14.0523 20.5523 14.5 20 14.5H17C16.4477 14.5 16 14.0523 16 13.5V10.5C16 9.9477 16.4477 9.5 17 9.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M4 16H7C7.5523 16 8 16.4477 8 17V20C8 20.5523 7.5523 21 7 21H4C3.4477 21 3 20.5523 3 20V17C3 16.4477 3.4477 16 4 16Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "5",
    },
  ],
  [
    "path",
    {
      d: "M10.5 16H13.5C14.0523 16 14.5 16.4477 14.5 17V20C14.5 20.5523 14.0523 21 13.5 21H10.5C9.9477 21 9.5 20.5523 9.5 20V17C9.5 16.4477 9.9477 16 10.5 16Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "6",
    },
  ],
  [
    "path",
    {
      d: "M17 16H20C20.5523 16 21 16.4477 21 17V20C21 20.5523 20.5523 21 20 21H17C16.4477 21 16 20.5523 16 20V17C16 16.4477 16.4477 16 17 16Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "7",
    },
  ],
];

export const PostgresqlIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M7.5 13.5C4.5 14 2.5 12 2.5 9C2.5 5.5 5 4 8 5.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M16.5 13.5C19.5 14 21.5 12 21.5 9C21.5 5.5 19 4 16 5.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M7.5 15.5C6.5 9.5 8.5 4 12 4C15.5 4 17.5 9.5 16.5 15.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M10 14V18.5C10 20.2 11.2 21.5 12.8 21.5C14 21.5 14.5 20.7 14.5 20M14 14V17",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M10 10H10.01M14 10H14.01",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
];

export const PrettierIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M4 3.5H14.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M4 7H7M10 7H12.5M15.5 7H18.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M4 10.5H8.5M15.5 10.5H19",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M4 14H14",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M4 17.5H7M10 17.5H11.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M4 21H7",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "5",
    },
  ],
];

export const PydanticIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M12 2.5L21.5 16L12 21.5L2.5 16L12 2.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M12 2.5V21.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M2.5 16H21.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const PytestIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M4 3H6.5M9.5 3H12M15 3H17.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M3.5 6.5H20.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M5 10V21",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M9.5 10V18.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M14 10V16",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M18.5 10V13",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "5",
    },
  ],
];

export const RadixUiIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M5.5 4.5C5.5 3.94772 5.94772 3.5 6.5 3.5H10.5C11.0523 3.5 11.5 3.94772 11.5 4.5V8.5C11.5 9.05228 11.0523 9.5 10.5 9.5H6.5C5.94772 9.5 5.5 9.05228 5.5 8.5V4.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "circle",
    {
      cx: "16",
      cy: "6.5",
      r: "3",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M11.5 12V21C9.01472 21 7 18.9853 7 16.5C7 14.0147 9.01472 12 11.5 12Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const RailwayIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "9.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M2.75 10H15.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M2.75 14H21.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const ReactHookFormIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M9 4.5H7C5.61929 4.5 4.5 5.61929 4.5 7V19C4.5 20.3807 5.61929 21.5 7 21.5H17C18.3807 21.5 19.5 20.3807 19.5 19V7C19.5 5.61929 18.3807 4.5 17 4.5H15",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M9 4.5C9 3.11929 10.3431 2 12 2C13.6569 2 15 3.11929 15 4.5V5.5H9V4.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M8 11H10.5M13.5 11H16M8 15.5H10.5M13.5 15.5H16",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const RuffIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M2.5 12C2.5 7.52166 2.5 5.28249 3.89124 3.89124C5.28249 2.5 7.52166 2.5 12 2.5C16.4783 2.5 18.7175 2.5 20.1088 3.89124C21.5 5.28249 21.5 7.52166 21.5 12C21.5 16.4783 21.5 18.7175 20.1088 20.1088C18.7175 21.5 16.4783 21.5 12 21.5C7.52166 21.5 5.28249 21.5 3.89124 20.1088C2.5 18.7175 2.5 16.4783 2.5 12Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M9 17V7H13.5C14.8807 7 16 8.11929 16 9.5C16 10.8807 14.8807 12 13.5 12H9M13 12L16 17",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const SpringBootIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.32966 8.88231C2.44322 10.4038 2 11.1646 2 12C2 12.8354 2.44322 13.5962 3.32966 15.1177L4.94031 17.8823C5.82675 19.4038 6.26997 20.1646 7 20.5823C7.73003 21 8.61647 21 10.3894 21H13.6106C15.3835 21 16.27 21 17 20.5823C17.73 20.1646 18.1733 19.4038 19.0597 17.8823L20.6703 15.1177C21.5568 13.5962 22 12.8354 22 12C22 11.1646 21.5568 10.4038 20.6703 8.88231L19.0597 6.11769C18.1733 4.59615 17.73 3.83538 17 3.41769C16.27 3 15.3835 3 13.6106 3H10.3894C8.61647 3 7.73003 3 7 3.41769C6.26997 3.83538 5.82675 4.59615 4.94031 6.11769L3.32966 8.88231Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M15.5 8.5C16.4 9.4 17 10.6 17 12C17 14.7614 14.7614 17 12 17C9.23858 17 7 14.7614 7 12C7 10.6 7.6 9.4 8.5 8.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M12 6.5V12",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
];

export const TanstackQueryIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M12.0001 8C17.5229 8 22.0001 9.79086 22.0001 12C22.0001 14.2091 17.5229 16 12.0001 16C6.47721 16 2.00006 14.2091 2.00006 12C2.00006 9.79086 6.47721 8 12.0001 8Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M15.5591 9.97529C18.3962 14.8173 19.1027 19.649 17.1371 20.7672C15.1715 21.8855 11.2781 18.8667 8.44104 14.0247C5.60395 9.18269 4.89746 4.35097 6.86306 3.23275C8.82865 2.11454 12.722 5.13327 15.5591 9.97529Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M15.5591 14.0247C12.722 18.8667 8.82865 21.8855 6.86306 20.7672C4.89746 19.649 5.60395 14.8173 8.44104 9.97529C11.2781 5.13327 15.1715 2.11454 17.1371 3.23275C19.1027 4.35097 18.3962 9.18269 15.5591 14.0247Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M12 9.75L13.9486 10.875L13.9486 13.125L12 14.25L10.0514 13.125L10.0514 10.875Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
];

export const TanstackIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "10",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M14.3678 11.8193C13.9574 10.2156 12.6917 9.0407 12 8.5991C12.25 8.333 12.9832 8.1289 13.75 8.3331C14.5168 8.5372 15.5 9.3972 15.5 10.7275C15.5 11.2407 15.345 11.6921 15.1471 12.0517C14.9427 12.423 14.4733 12.2315 14.3678 11.8193Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M14.3079 6.25C12.4616 6.25 12 7.75 12 8.5C13.4336 7.7235 14.9599 7.8514 15.9308 8.0644C16.2723 8.1393 16.5992 7.8925 16.4718 7.5747C16.2234 6.9547 15.61 6.25 14.3079 6.25Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M9.1983 5.75C8.3028 5.75 7.7626 6.1524 7.5377 6.5642C7.4132 6.7921 7.6157 7.0175 7.8768 7.0519C8.9554 7.1943 10.773 7.5618 12 8.25C11.7453 7.25 10.9812 5.75 9.1983 5.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M12.5 9.25C12.4167 10.6667 12.25 12.75 11.5 15.25",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M10.25 7.75C11.25 7.75 11.75 8.309 12 8.5885C9.9624 9.2719 9.0873 10.3266 8.5626 11.4501C8.3964 11.8057 7.9864 11.8753 7.8752 11.4938C7.7989 11.2322 7.75 10.9159 7.75 10.545C7.75 8.5885 9.5 7.75 10.25 7.75Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "5",
    },
  ],
  [
    "path",
    {
      d: "M6 16.5C7.5 15.7 9 15.7 10.5 16.5C12 17.3 13.5 17.3 15 16.5C16.5 15.7 17 15.7 18 16",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "6",
    },
  ],
];

export const TurborepoIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "12",
      r: "4",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M4.2181 6.551A9.5 9.5 0 1 1 6.551 19.7819",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M5.8935 19.2774A9.5 9.5 0 0 1 3.7728 16.75",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M3.0729 15.2492A9.5 9.5 0 0 1 2.5 12",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M2.6443 10.3503A9.5 9.5 0 0 1 3.3901 7.9851",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
];

export const UvIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.5 4.5C3.5 3.94772 3.94772 3.5 4.5 3.5H8.5C9.05228 3.5 9.5 3.94772 9.5 4.5V14.5H14.5V4.5C14.5 3.94772 14.9477 3.5 15.5 3.5H19.5C20.0523 3.5 20.5 3.94772 20.5 4.5V20.5H4.5C3.94772 20.5 3.5 20.0523 3.5 19.5V4.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
];

export const VaadinIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3 3.5V5.5C3 6.88071 4.11929 8 5.5 8H9.5C10.8807 8 12 9.11929 12 10.5C12 9.11929 13.1193 8 14.5 8H18.5C19.8807 8 21 6.88071 21 5.5V3.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M7.5 11.5L12 20.5L16.5 11.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const VercelIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M10.2679 4.5C11.0377 3.16667 12.9623 3.16667 13.7321 4.5L20.6603 16.5C21.4301 17.8333 20.4678 19.5 18.9282 19.5H5.0718C3.5322 19.5 2.56995 17.8333 3.33975 16.5L10.2679 4.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
];

export const ViteIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M6 2.5H20L16 8.5H21L12 21.5V15.5H4.5L9 9H3L6 2.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
];

export const VitestIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3 11.5L6.5 9L10.5 14L18 3.5L21 5.5L10.5 20.5L3 11.5Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
];

export const ZedIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M3.5 17V5C3.5 4.17157 4.17157 3.5 5 3.5H17",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M20.5 7V19C20.5 19.8284 19.8284 20.5 19 20.5H7",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M3.5 20.5L20.5 3.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M7.5 13V7.5H13",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M16.5 11V16.5H11",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
];

export const ZodIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M6.5 4H17.5L21.5 9L12 20.5L2.5 9L6.5 4Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M8.5 8H15.5L9.5 13.5H15",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
];

export const ZustandIcon: IconSvgElement = [
  [
    "circle",
    {
      cx: "12",
      cy: "13.5",
      r: "7.5",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M6.0084 8.9889A3 3 0 1 1 8.6433 6.7931",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M15.3567 6.7931A3 3 0 1 1 17.9916 8.9889",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M9.5 12H9.51M14.5 12H14.51",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M10.5 16C10.5 15.2 11.2 14.75 12 14.75C12.8 14.75 13.5 15.2 13.5 16C13.5 16.8 12.8 17.25 12 17.25C11.2 17.25 10.5 16.8 10.5 16Z",
      stroke: "currentColor",
      strokeWidth: "1.5",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      key: "4",
    },
  ],
];
